apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-sleeper
  namespace: dev
spec:
  replicas: 5
  selector:
    matchLabels:
      app: sleeper
  template:
    metadata:
      labels:
        app: sleeper
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ["sleep", "3600"]
