apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: redis
spec:
  clusterIP: None        # Headless Service для внутрішнього DNS
  selector:
    app: redis
  ports:
    - port: 6379         # Порт Redis